### ISSUE TITLE
recipe for target 'src/regex.o' failed

### ISSUE THREAD

**Issue by 097115** [eafer/rdrview#1]
Fails on Ubuntu 16.04 (gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0):

    gcc -DNDEBUG -O2 -Wall -Wextra -fno-strict-aliasing  -I/usr/include/libxml2 -o src/regex.o -c src/regex.c
    src/regex.c:95:2: error: initializer element is not constant
      UNLIKELY_RE, CANDIDATE_RE, BYLINE_RE, PROPERTY_RE, NAME_RE, IMGEXT_RE,
      ^
    src/regex.c:95:2: note: (near initialization for ‘REGEXES[0]’)
    src/regex.c:95:15: error: initializer element is not constant
      UNLIKELY_RE, CANDIDATE_RE, BYLINE_RE, PROPERTY_RE, NAME_RE, IMGEXT_RE,
                   ^
    src/regex.c:95:15: note: (near initialization for ‘REGEXES[1]’)
    src/regex.c:95:29: error: initializer element is not constant
      UNLIKELY_RE, CANDIDATE_RE, BYLINE_RE, PROPERTY_RE, NAME_RE, IMGEXT_RE,
                                 ^
    src/regex.c:95:29: note: (near initialization for ‘REGEXES[2]’)
    src/regex.c:95:40: error: initializer element is not constant
      UNLIKELY_RE, CANDIDATE_RE, BYLINE_RE, PROPERTY_RE, NAME_RE, IMGEXT_RE,
                                            ^
    src/regex.c:95:40: note: (near initialization for ‘REGEXES[3]’)
    src/regex.c:95:53: error: initializer element is not constant
      UNLIKELY_RE, CANDIDATE_RE, BYLINE_RE, PROPERTY_RE, NAME_RE, IMGEXT_RE,
                                                         ^
    src/regex.c:95:53: note: (near initialization for ‘REGEXES[4]’)
    src/regex.c:95:62: error: initializer element is not constant
      UNLIKELY_RE, CANDIDATE_RE, BYLINE_RE, PROPERTY_RE, NAME_RE, IMGEXT_RE,
                                                                  ^
    src/regex.c:95:62: note: (near initialization for ‘REGEXES[5]’)
    src/regex.c:96:2: error: initializer element is not constant
      HASCONTENT_RE, NEGATIVE_RE, POSITIVE_RE, SENTENCE_DOT_RE, B64_DATAURL_RE,
      ^
    src/regex.c:96:2: note: (near initialization for ‘REGEXES[6]’)
    src/regex.c:96:17: error: initializer element is not constant
      HASCONTENT_RE, NEGATIVE_RE, POSITIVE_RE, SENTENCE_DOT_RE, B64_DATAURL_RE,
                     ^
    src/regex.c:96:17: note: (near initialization for ‘REGEXES[7]’)
    src/regex.c:96:30: error: initializer element is not constant
      HASCONTENT_RE, NEGATIVE_RE, POSITIVE_RE, SENTENCE_DOT_RE, B64_DATAURL_RE,
                                  ^
    src/regex.c:96:30: note: (near initialization for ‘REGEXES[8]’)
    src/regex.c:96:43: error: initializer element is not constant
      HASCONTENT_RE, NEGATIVE_RE, POSITIVE_RE, SENTENCE_DOT_RE, B64_DATAURL_RE,
                                               ^
    src/regex.c:96:43: note: (near initialization for ‘REGEXES[9]’)
    src/regex.c:96:60: error: initializer element is not constant
      HASCONTENT_RE, NEGATIVE_RE, POSITIVE_RE, SENTENCE_DOT_RE, B64_DATAURL_RE,
                                                                ^
    src/regex.c:96:60: note: (near initialization for ‘REGEXES[10]’)
    src/regex.c:97:2: error: initializer element is not constant
      SRCSET_RE, SRC_RE, VIDEOS_RE, SHARE_RE, ABSOLUTE_RE,
      ^
    src/regex.c:97:2: note: (near initialization for ‘REGEXES[11]’)
    src/regex.c:97:13: error: initializer element is not constant
      SRCSET_RE, SRC_RE, VIDEOS_RE, SHARE_RE, ABSOLUTE_RE,
                 ^
    src/regex.c:97:13: note: (near initialization for ‘REGEXES[12]’)
    src/regex.c:97:21: error: initializer element is not constant
      SRCSET_RE, SRC_RE, VIDEOS_RE, SHARE_RE, ABSOLUTE_RE,
                         ^
    src/regex.c:97:21: note: (near initialization for ‘REGEXES[13]’)
    src/regex.c:97:32: error: initializer element is not constant
      SRCSET_RE, SRC_RE, VIDEOS_RE, SHARE_RE, ABSOLUTE_RE,
                                    ^
    src/regex.c:97:32: note: (near initialization for ‘REGEXES[14]’)
    src/regex.c:97:42: error: initializer element is not constant
      SRCSET_RE, SRC_RE, VIDEOS_RE, SHARE_RE, ABSOLUTE_RE,
                                              ^
    src/regex.c:97:42: note: (near initialization for ‘REGEXES[15]’)
    Makefile:18: recipe for target 'src/regex.o' failed
    make: *** [src/regex.o] Error 1

**Comment by eafer** [comment]
Thanks for the report. It seems that older versions of gcc don't allow you to initialize an array with this kind of constant expressions. I'll have to change it.

**Comment by eafer** [comment]
I replaced the constant strings with macros and now it builds with gcc 4.9.2. When you can, let me know if it works for you too.

**Comment by 097115** [comment]
Indeed, it worked! Thanks!
